"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authController_1 = require("../controllers/authController");
var validate_1 = require("../middlewares/validate");
var authValidation_1 = require("../utils/validations/authValidation");
var authRouter = (0, express_1.Router)();
authRouter.post('/signUp', (0, validate_1.validate)(authValidation_1.signUpUserSchema), authController_1.signUpUser);
authRouter.post('/login', (0, validate_1.validate)(authValidation_1.loginUserSchema), authController_1.login);
exports.default = authRouter;
