"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var categoryController_1 = require("../controllers/categoryController");
var validate_1 = require("../middlewares/validate");
var categoryValidation_1 = require("../utils/validations/categoryValidation");
var categoryRoute = (0, express_1.Router)();
categoryRoute.post('/', (0, validate_1.validate)(categoryValidation_1.createCategorySchema), categoryController_1.createCategory);
categoryRoute.get('/', categoryController_1.getCategories);
exports.default = categoryRoute;
